source 'https://rubygems.org'

gem 'rails', '3.2.13'

gem 'sqlite3'

gem 'devise'
gem 'haml-rails'

gem 'spawnling'

# Inline edition
gem 'best_in_place'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'carrierwave'
gem 'treetop'
gem 'uci', path: '../uci-0.0.2/'

gem 'will_paginate', '~> 3.0'

gem 'slim', ">= 1.3.0"

group :development do
  gem 'thin'
  gem 'quiet_assets'
  gem 'pkgr'
end

group :test do
  gem 'factory_girl_rails'
end
#
# Use unicorn as the app server
group :production do
  gem 'thin'
end
